# Cloud Build configuration for automatic deployment
# This file enables CI/CD from GitHub to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-native-crm-backend', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-native-crm-backend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-native-crm-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-native-crm-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

# Images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ai-native-crm-backend'

# Build timeout
timeout: 1200s

# Substitutions (optional)
substitutions:
  _REGION: us-central1
  _SERVICE_NAME: ai-native-crm-backend

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

